nc:
  gnn:
    node_encoder: gcn
    hidden_dim: 256
    output_dim: 128
    num_layers: 2
    dropout: 0.2
    activation: elu
    dropout: 0.2
    bn: True
    dec_heads: 2
  mlp:
    hidden_dim: 32
    num_layers: 1
    dropout: 0.5
  q1_size: 256
  temp_decay: 0.2
  q2_size: 32
  alpha: 1.
  beta: 1.
  vq_type: 2
  max_epochs: 100
lp:
  gnn:
    node_encoder: gcn
    hidden_dim: 128
    output_dim: 128
    num_layers: 1
    dropout: 0.2
    activation: elu
    bn: True
  mlp:
    hidden_dim: 64
    num_layers: 2
    dropout: 0.5
  q1_size: 256
  t0: 0.1
  temp_decay: 0.1
  q2_size: 16
  alpha: 1.
  beta: 0.1
  vq_type: 1
  val_freq: 20
  max_epochs: 1000
  patience: 20
  optimizer:
    lr: 0.01
    type: adamw
    weight_decay: 0.005