nc:
  gnn:
    node_encoder: gcn
    hidden_dim: 256
    output_dim: 256
    num_layers: 2
    dropout: 0.2
    activation: elu
    dropout: 0.2
    concat: true
    bn: True
  mlp:
    hidden_dim: 32
    num_layers: 2
    dropout: 0.5
  q1_size: 32
  t0: 0.1
  q2_size: 8
  lambda_: 3
  alpha: 1.
  beta: 0.01
  l2_norm: false
  max_epochs: 3000
lp:
  gnn:
    node_encoder: gcn
    hidden_dim: 128
    output_dim: 64
    num_layers: 3
    dropout: 0.2
    activation: elu
    bn: True
  mlp:
    hidden_dim: 64
    num_layers: 2
    dropout: 0.5
  q1_size: 256
  temp_decay: 0.3
  q2_size: 32
  lambda_: 1
  alpha: 1.
  val_freq: 50
  max_epochs: 1000