nc:
  gnn:
    node_encoder: gcn
    hidden_dim: 512
    output_dim: 256
    num_layers: 2
    activation: elu
    dropout: 0.2
    bn: True
    dec_heads: 2
  mlp:
    hidden_dim: 32
    num_layers: 2
    dropout: 0.2
  q1_size: 1024
  t0: 1.
  temp_decay: 0.9
  q2_size: 128
  lambda_: 1
  alpha: 1.
  beta: 0.1
  max_epochs: 500
lp:
  gnn:
    node_encoder: gcn
    hidden_dim: 128
    output_dim: 128
    num_layers: 1
    dropout: 0.2
    activation: elu
    bn: True
    dec_heads: 1
  mlp:
    hidden_dim: 32
    num_layers: 2
    dropout: 0.5
  q1_size: 256
  temp_decay: 0.3
  q2_size: 16
  lambda_: 1
  alpha: 1.
  beta: 1.
  vq_type: 2
  val_freq: 50
  optimizer:
    type: adam
    lr: 0.01
    weight_decay: 0.
  scheduler: null
  max_epochs: 500