nc:
  gnn:
    node_encoder: gcn
    hidden_dim: 64
    output_dim: 64
    num_layers: 2
    activation: elu
    dropout: 0.2
    concat: True
    bn: True
    dec_heads: 2
  mlp:
    hidden_dim: 32
    num_layers: 2
    dropout: 0.5
  q1_size: 512
  t0: 0.1
  temp_decay: 0.1
  q2_size: 16
  alpha: 1.
  beta: 0.01
  l2_norm: false
  max_epochs: 500
lp:
  gnn:
    node_encoder: gcn
    hidden_dim: 128
    output_dim: 32
    num_layers: 1
    dropout: 0.2
    activation: elu
    bn: True
    dec_heads: 4
  mlp:
    hidden_dim: 32
    num_layers: 1
    dropout: 0.5
  q1_size: 64
  temp_decay: 0.1
  q2_size: 8
  alpha: 1.
  vq_type: 2
  val_freq: 50
  max_epochs: 1000