nc:
  gnn:
    node_encoder: gcn
    hidden_dim: 2048
    output_dim: 512
    num_layers: 3
    activation: elu
    dropout: 0.2
    bn: True
  mlp:
    hidden_dim: 512
    num_layers: 3
    dropout: 0.
  q1_size: 2048
  q2_size: 256
  lambda_: 3
  alpha: 1.
  beta: 0.01
  num_neighbors: [32, 32]
  batch_size: 1024
  drop_edge_rate: 0.3
  max_epochs: 5
  num_workers: 4
  optimizer:
    lr: 1.0e-5
    type: adamw
    weight_decay: 5.0e-5