nc:
  gnn:
    node_encoder: gcn
    hidden_dim: 256
    output_dim: 128
    num_layers: 2
    activation: elu
    dropout: 0.2
    bn: True
  mlp:
    hidden_dim: 256
    num_layers: 3
    dropout: 0.2
  q1_size: 64
  q2_size: 16
  lambda_: 1
  alpha: 1.
  max_epochs: 500
lp:
  gnn:
    node_encoder: gcn
    hidden_dim: 128
    output_dim: 64
    num_layers: 3
    dropout: 0.2
    activation: elu
    bn: True
  mlp:
    hidden_dim: 64
    num_layers: 2
    dropout: 0.5
  q1_size: 256
  temp_decay: 0.3
  q2_size: 32
  lambda_: 2
  alpha: 1.
  val_freq: 50
  max_epochs: 1000