nc:
  gnn:
    node_encoder: gcn
    hidden_dim: 256
    output_dim: 256
    num_layers: 2
    activation: elu
    dropout: 0.2
    concat: true
    bn: True
    dec_heads: 2
  mlp:
    hidden_dim: 32
    num_layers: 2
    dropout: 0.5
  q1_size: 512
  t0: 0.5
  temp_decay: 0.5
  q2_size: 128
  lambda_: 3
  alpha: 1.
  beta: 0.01
  quantizer:
    type: adam
    lr: 0.01
    weight_decay: 0.
  max_epochs: 500
lp:
  gnn:
    node_encoder: gcn
    hidden_dim: 512
    output_dim: 128
    num_layers: 1
    dropout: 0.5
    dec_dropout: 0.2
    activation: elu
    bn: True
  mlp:
    hidden_dim: 32
    num_layers: 2
    dropout: 0.5
  q1_size: 256
  t0: 1.
  temp_decay: 0.3
  q2_size: 8
  lambda_: 2
  alpha: 1.
  beta: 0.01
  vq_type: 2
  val_freq: 50
  max_epochs: 1000
  optimizer:
    type: adam
    lr: 0.01
    weight_decay: 0.0
  scheduler: null